version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - "./server:/usr/src"
      - "django_init:/usr/src/init"
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - "./client/mysite:/usr/src"
    ports:
      #  - "8080:8080"
      - "5173:5173"
    tty: true
    stdin_open: true
    depends_on:
      - server
    environment:
      - NODE_ENV=development
volumes:
  django_init: # 初期化フラグ用のボリュームを定義
