POST http://localhost:8000/api-token-auth/
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

### c8b1210075a4fe55141616826ae6413282057032

POST http://localhost:8000/api/member/
Content-Type: application/json

{
  "username": "tester02",
  "email": "test02@co.jp",
  "password": "test"
}

###
# @prompt token

GET http://localhost:8000/api/member/
Content-Type: application/json
Authorization: Token {{token}}

###
# @prompt token

GET http://localhost:8000/api/booklisttype/?owner_id=da810266-c792-45f3-850a-1ab4a73ebeaf
Content-Type: application/json
Authorization: Token {{token}}


###
# @prompt token

GET http://localhost:8000/api/booklist/?booklisttype_id=e1a98696-bad2-4836-9133-df62f5ebf156&member_id=da810266-c792-45f3-850a-1ab4a73ebeaf
Content-Type: application/json
Authorization: Token {{token}}


###
# @prompt token

PUT http://localhost:8000/api/book/bulk_update/
Content-Type: application/json
Authorization: Token {{token}}

{
  "books": [
    {
      "id": "26d0b979-a4f7-4caf-8092-b065bb6cdd10",
      "booklist": "39e647f9-73ea-436f-b5f3-d0f7d4cae028",
      "title": "Updated Title 1",
      "description": "Updated Description 1",
      "image": "http://0.0.0.0:8000/media/example.png",
      "order": 1
    }
  ],
  "id": "39e647f9-73ea-436f-b5f3-d0f7d4cae028",
  "is_completed": true
}
