# Generated by Django 4.0.2 on 2024-11-07 16:32

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='未登録', max_length=100, verbose_name='タイトル')),
                ('description', models.CharField(default='未登録', max_length=2000, verbose_name='概要')),
                ('image', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='イメージ図')),
                ('order', models.IntegerField(verbose_name='本順')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False, verbose_name='作成状況')),
            ],
        ),
        migrations.CreateModel(
            name='BookListType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100, verbose_name='種類')),
            ],
        ),
        migrations.CreateModel(
            name='RecBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='未登録', max_length=100, verbose_name='タイトル')),
                ('description', models.CharField(default='未登録', max_length=2000, verbose_name='概要')),
                ('image', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='イメージ図')),
                ('rec_method', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('pca_avg_vector_normal', 'PCA平均ベクトル(重みなし)'), ('pca_avg_vector_weighted', 'PCA平均ベクトル(重みあり)'), ('collaborative', '協調フィルタリング'), ('w2v_avg_vector', 'Word2Vec平均ベクトル')], max_length=74, verbose_name='推薦手法')),
                ('want_to_see', models.BooleanField(default=False, verbose_name='読みたいフラグ')),
                ('want_to_rewatch', models.BooleanField(default=False, verbose_name='ランキングインフラグ')),
                ('booklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recbooklist', to='books.booklist')),
            ],
        ),
    ]
