# Generated by Django 4.0.2 on 2024-11-07 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='いいね'),
        ),
        migrations.AddField(
            model_name='booklist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_booklists', to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
        migrations.AddField(
            model_name='booklist',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booklisttype', to='books.booklisttype'),
        ),
        migrations.AddField(
            model_name='book',
            name='booklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booklist', to='books.booklist'),
        ),
    ]
